name: QQ阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '5 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQ_QQreadURL: ${{ secrets.QQ_QQreadURL }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/LxgLxgLxg/ScriptCopy_ziye.git ~/ScriptCopy_ziye
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.QQ_QQreadURL
        run: |
          cd ~/ScriptCopy_ziye
          git checkout main
          npm install
      - name: '运行 【QQ阅读】'
        if: env.QQ_QQreadURL
        run: |
          cd ~/ScriptCopy_ziye
          node Task/QQread.js
