name: 易趣牛帮

on:
  workflow_dispatch:
  schedule:
     - cron: '2,32 20-23,0-14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YQNB_yqnbHEADER: ${{ secrets.YQNB_yqnbHEADER }}
        YQNB_yqnbBODY: ${{ secrets.YQNB_yqnbBODY }}
        YQNB_yqnbsjHEADER: ${{ secrets.YQNB_yqnbsjHEADER }}
        YQNB_yqnbsjBODY: ${{ secrets.YQNB_yqnbsjBODY }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Lxg2/ScriptCopy_ziye.git ~/ScriptCopy_ziye
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YQNB_yqnbHEADER
        run: |
          cd ~/ScriptCopy_ziye
          git checkout main
          npm install
      - name: '运行 【易趣牛帮】'
        if: env.YQNB_yqnbHEADER
        run: |
          cd ~/ScriptCopy_ziye
          node Task/yqnb.js
