name: 步步宝

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BBB_bububaoTOKEN: ${{ secrets.BBB_bububaoTOKEN }}
        BBB_CASH: ${{ secrets.BBB_CASH }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/LxgLxgLxg/ScriptCopy_ziye.git ~/ScriptCopy_ziye
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.BBB_bububaoTOKEN
        run: |
          cd ~/ScriptCopy_ziye
          git checkout main
          npm install
      - name: '运行 【步步宝】'
        if: env.BBB_bububaoTOKEN
        run: |
          cd ~/ScriptCopy_ziye
          node Task/bububao.js
