name: 笑谱

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 0-11 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
        XP_live: ${{ secrets.XP_live }}
        XP_iboxpayvideoHEADER: ${{ secrets.XP_iboxpayvideoHEADER }}
        XP_iboxpayvideoBODY: ${{ secrets.XP_iboxpayvideoBODY }}
        XP_CASH: ${{ secrets.XP_CASH }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Lxg2/ScriptCopy_ziye.git ~/ScriptCopy_ziye
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_refreshTOKEN
        run: |
          cd ~/ScriptCopy_ziye
          git checkout main
          npm install
      - name: '运行 【笑谱】'
        if: env.XP_refreshTOKEN
        run: |
          cd ~/ScriptCopy_ziye
          node Task/iboxpay.js
